### ISSUE TITLE
Can't access profile

### ISSUE THREAD

**Issue by damienjoatu** [joatuapp/joatu-app#10]
When clicking on my username (not correctly displayed, see issue #9), none of the links work (My Profile, Edit Profile, etc. do not do anything)

![image](https://cloud.githubusercontent.com/assets/8975423/4463864/be23f134-48ce-11e4-991c-ab73117f2e29.png)

**Comment by undergroundwebdesigns** [comment]
That is definitely a bug. Nearly all of those links are supposed to work, except the last two, My Friends and My Community. Shall I just remove those two? While I figure out why the rest don't work...
