### ISSUE TITLE
Community not saving on profile edit page

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-app#15]
![image](https://cloud.githubusercontent.com/assets/5350076/4465480/ffc0fa08-48db-11e4-9963-934e89cb6f58.png)

I put in my postal code and it doesn't save.

Also, "unknown" isn't spelled correctly.

**Comment by undergroundwebdesigns** [comment]
It's not saving because it didn't actually find any communities (I don't think there are any right now). It's telling you that (below search box, in white), but maybe we need to make it clearer what's going wrong?

**Comment by undergroundwebdesigns** [comment]
@joatu I think this is more of a UI issue than a bug (besides the typo, which I've fixed). We need to decide how we want the interface for choosing a community to work. What happens if there are no communities near your location? How can we make it clearer what's going on here?

**Comment by joatu** [comment]
This might be overly complex for this stage of development, but what about
a 'start a community' option if nothing comes up.  We then have a page that
walks them through naming a community and setting an appropriate location.
This ultimately needs to be approved by us, but we'll make filling out the
form as clear as possible to limit confusion and complications.

I can work on creating the pages categories ASAP if you imagine integrating
this soon.  It can auto-forward to the JoatU team email for now and we can
have it function through the site at a later date.

Also, as a feature, the "# of users needed to launch" per community labeled
in brackets when the community is selected.

**Comment by undergroundwebdesigns** [comment]
Marking this #request-for-comment, as I think it's related to the ongoing discussion on issue #19, and we should make some decisions before we act on it. As I expressed there, I really don't think limiting the use of the site until a community somehow "launches" is useful. If anything, I'd say we should be approaching it from the opposite direction. What about this:

When you register, if there are no communities nearby, that's fine, you don't join any, and we note where you live. Then we have a tool (in the admin area) that detects when a group of people is in an area, and notes it if that group gets over a certain size. So as people join in a neighbourhood, it notifies the admins, and then we can create a community there and add them all too it? Until the community is put in place, the search could by default cover a much larger surrounding area, in an attempt to be useful, but with a bar at the top explaining how JoatU is more useful in close communities, and linking to how people can invite their friends & neighbours to join.... maybe even showing how many people in their neighbourhood have joined so far....

What do you think of that @joatu? Similar to your idea, but more likely to help us grow, I would think.

**Comment by joatu** [comment]
Hah, this is an ever-so-slight variation on what I just typed for another
bug.  I like it.   The only change is that I want to require a min-amount
for the first community within a city.  Frankly, if it isn't a lot of work,
I'd be happy to try it both ways and see what happens.  I personally
believe that requiring 50 people to join isn't a lot at all and that it
will create incentive to the very first users to make their friends become
members and then having that minimum amount will be appealing to a lot more
people, knowing that when you join, you'll have at least 50 people to
exchange with right off the bat instead of feeling like you have to keep
coming back to see if there's anything new or interesting.  With 50+, you
know there will be right away.

**Comment by undergroundwebdesigns** [comment]
I believe the results of this discussion are rolled into issue #40, so closing this one.
