### ISSUE TITLE
Hitting the login button after the sign up button makes both forms show at the same time

### ISSUE THREAD

**Issue by jmiv** [joatuapp/joatu-app#16]
Not sure if it's a bug. After I click the sign up button, then go back to clicking the log in button, I expect the previous sign up form to disappear immediately once the log in form comes up. Instead the log in form just pops on top of the sign in form. I suggest to make these forms show up only one at a time.

Using Chrome Version 37.0.2062.124 m

![joatu_screenshot](https://cloud.githubusercontent.com/assets/8285782/4466260/f776860e-48e2-11e4-9191-06bd66256cfe.png)

**Comment by undergroundwebdesigns** [comment]
I'd say not a bug. The login form always just pops up on top of whatever else you happened to be doing at the time.
