### ISSUE TITLE
Radius of communities

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-app#17]
Please set natural radius to 2km.

**Comment by TedEwanchyna** [comment]
i can take a look at this. it seems that this would fix it:
app/models/community.rb:    distance_in_meters ||= 5000
change 5000 to 2000
May have to change spec to test, as hostname is not set via variable
-Ted

**Comment by undergroundwebdesigns** [comment]
Sounds good @TedEwanchyna, do it.

**Comment by undergroundwebdesigns** [comment]
Done, I'm just about to push it to the alpha site as well. Closing.
