### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-app#18]
- Allow users to submit & have their locations saved whether or not there is a community within their vicinity.

**Comment by undergroundwebdesigns** [comment]
We actually already do this, but I agree the interface is not clear at all. Right now, if there are one or more communities near the address you entered, a select box shows up and you get to pick which one you wish to be "primarily" associated with. If there are no communities, it says so, but still grabs the location data to save to your profile when you save the form or hit register. 

Like I said, not great. How do you think it should work?

**Comment by joatu** [comment]
It wasn't saving my location in my profile when there wasn't a community nearby.  Perhaps this isn't an enhancement then, just a bug?

As far as the rest of what you said, I think it's fine for the time being.  I can't think of a better way right now.

**Comment by undergroundwebdesigns** [comment]
Might be just a bug then. Bear in mind, I never coded anything to _display_ this information anywhere. It gets stored and that's it (for now). Your account does have location data (I just checked) and I did a quick look earlier and saw there were a few other accounts besides ours that have location data, so it seems to be working to me.

**Comment by joatu** [comment]
Everyone should have their location data stored if they've created a user account then.  If any accounts are missing that data, is that to say they bypassed submitting it in the registration?

**Comment by undergroundwebdesigns** [comment]
I don't think there's anything in the code that _requires_ someone to enter a location, so I think you can just ignore the field altogether (right now). Requiring location info (whether or not there is a community) is something we can do though.

**Comment by joatu** [comment]
Yes, let's make it a requirement for registration please.

**Comment by undergroundwebdesigns** [comment]
As per discussion, the task here is simply to make sure that each registering user enters some address information, lets say to at least the city level. The existing code uses the Google API's to populate a number of hidden input fields, so ensuring that that code populates the city field and erroring if not should cover this.

**Comment by undergroundwebdesigns** [comment]
Closing this as it's proposals are covered more succinctly in issue #40
