### ISSUE TITLE
Home page / Login and Signup buttons not responding.

### ISSUE THREAD

**Issue by CatherineBourgeois** [joatuapp/joatu-app#20]

**Comment by joatu** [comment]
This needs a description (and a tag).  How can someone else replicate this issue?  What browser are you using?

**Comment by joatu** [comment]
I can reproduce this error using Firefox 32.0.3.  Login & Signup buttons do nothing.

**Comment by undergroundwebdesigns** [comment]
Possible duplicate of #24
