### ISSUE TITLE
upper-right menu unresponsive after search

### ISSUE THREAD

**Issue by johnnycoull** [joatuapp/joatu-app#24]
Was not able to click on any items in upper-right menu (under screen name) after initially signing up and trying to use the search. Since then, it's been working for me, so it might just be an issue for new accounts.

**Comment by johnnycoull** [comment]
happened again after I confirmed my e-mail address and re-opened the site.

**Comment by undergroundwebdesigns** [comment]
This should have been fixed with the fix for #20, which went live just now. Please re-open if you can reproduce again.
