### ISSUE TITLE
Remove X button, place 'logout' in top-right list

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-app#25]
Watching Johnny use the site, he accidentally logged out numerous times mistaking the X in the corner to mean a way to close an opened window within JoatU.  I would suggest we remove it entirely and replace it with a button that will send people to a random person's profile within their community. 

The logout option can be in the drop-down list on the top right.

**Comment by undergroundwebdesigns** [comment]
Seems like a good idea to me.

**Comment by undergroundwebdesigns** [comment]
Wait, when I previously read this I missed the part about sending people to a random profile within their community... can we skip that for now, and just move the "logout" to be spelled out? I really don't think a button that randomly brings you to some stranger's profile for no good reason makes any sense at all...

**Comment by joatu** [comment]
Agreed.

**Comment by TedEwanchyna** [comment]
can i look at this?
(how do i get assigned? do you assign this to me or do i assign it to myself or do i just comment here
and then do a pull request?)

**Comment by TedEwanchyna** [comment]
I commented out the original logout code. The idea is it would be easier to put it back if we need to (I know, we are using git, so this is not necessary...). I thought, perhaps, we could add a "are you sure", instead of logging the person out. I added the logout to the menu on the right.
