### ISSUE TITLE
Nothing appearing in My Profile page / pull-down menu not responding <bug>

### ISSUE THREAD

**Issue by CatherineBourgeois** [joatuapp/joatu-app#29]
Mac OS X 10.9.4 2.5 GHz Intel Core i7 16 G. 1600 MHz DDR3
running Safari Version 7.0.6 (9537.78.2)
after signing in immediately selecting My Profile from the pull down menu.
Pull-down menu not responsive and disappears when the "x" is clicked.
Then, empty page.
After refresh (key command shortcut), the site seams to work fine.

**Comment by undergroundwebdesigns** [comment]
This should now be fixed (same fix as #20), though please feel free to re-open if you see it still happening.
