### ISSUE TITLE
Save button seems not working in Profile page

### ISSUE THREAD

**Issue by CatherineBourgeois** [joatuapp/joatu-app#30]
Mac OS X 10.9.4 2.5 GHz Intel Core i7 16 G. 1600 MHz DDR3
running Safari Version 7.0.6 (9537.78.2)
after (see last bug report for previous actions), 
updating community info in Profile page
clicking save does not seem to update community info into the page.
I then refreshed the page (cmd-R) and the info updated correctly.

**Comment by undergroundwebdesigns** [comment]
I can confirm. On saving the form, the community name should appear under the heading "Current Community" immediately, without requiring a refresh.
