### ISSUE TITLE
Change background to Green Image all the time, not just on mobile.

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-app#33]
Not sure if we should consider this a bug or a feature.  Was this done on purpose?

When I shrink the window:

![green - when small](https://cloud.githubusercontent.com/assets/5350076/4876287/6db5f6c0-62be-11e4-90e4-910768de5a5b.png)

When I expand the window:

![normal - when expanded](https://cloud.githubusercontent.com/assets/5350076/4876447/6e44dce4-62c5-11e4-99a0-ea7a90d8b594.png)

**Comment by joatu** [comment]
Can you please remove the arty background and we'll just use the pure green throughout?

**Comment by undergroundwebdesigns** [comment]
@joatu FYI yes, it was intended that the background change colours like that. The artsy background cuts off (as can be seen in your screenshot) and looks bad at small sizes, especially on mobile devices, so I configured the site to use the green one there. 

I do agree that the green background is better cross-site, and have re-named this bug accordingly.

**Comment by TedEwanchyna** [comment]
i will fix

**Comment by TedEwanchyna** [comment]
ok, i fixed it. again i commented out the offending code
