### ISSUE TITLE
Sign-Up - 1/2 buttons being on top instead of left-right

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-app#34]
They used to be one in front of the other.  It makes more sense for these button shapes.

![top or leftright](https://cloud.githubusercontent.com/assets/5350076/4876636/d4d34462-62cc-11e4-8032-3666a7bfabbb.png)

**Comment by joatu** [comment]
Could be related to the same issue, but when I move to the second page, 1 is still highlighted in orange.

**Comment by undergroundwebdesigns** [comment]
I'm marking this wont-fix, and closing it, as we've agreed to move towards a simpler login form, so this two-step UI feature is no longer needed.
