### ISSUE TITLE
Tags do not link to search

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-app#7]
Clicking on any tags (currency or offers) do not link to anything.  I believe they should link to a search within our local community (with the possibility of being extended within the search to a larger community).

**Comment by undergroundwebdesigns** [comment]
For now, lets just have the tags on an offer link to a search for that tag. The search system isn't very sophisticated yet, so there's nothing really useful to link currency tags to (yet).

**Comment by joatu** [comment]
Agreed.  Mentioned in [Issue 51](https://github.com/joatuapp/joatu-app/issues/51).

**Comment by TedEwanchyna** [comment]
i can make the tags be clickable and do search based on the tag  contents
